# spiritty_embed_shaders(OUTPUT <header_path> SHADERS <file1> <file2> ...)
#
# Generates a C header containing each input shader as a static const char*
# constant. The constant name is derived from the file's basename:
#   common.glsl          -> sp_shader_common
#   cell_text.v.glsl     -> sp_shader_cell_text_v
#   cell_text.f.glsl     -> sp_shader_cell_text_f
#   shadertoy_prefix.glsl-> sp_shader_shadertoy_prefix
#
# Re-runs at build time whenever any input changes. Uses CMake's own
# file(READ ...) so there's no host-tool dependency (no xxd, no python).

function(spiritty_embed_shaders)
    cmake_parse_arguments(SES "" "OUTPUT" "SHADERS" ${ARGN})
    if(NOT SES_OUTPUT)
        message(FATAL_ERROR "spiritty_embed_shaders: OUTPUT is required")
    endif()
    if(NOT SES_SHADERS)
        message(FATAL_ERROR "spiritty_embed_shaders: SHADERS is required")
    endif()

    set(_script "${CMAKE_CURRENT_BINARY_DIR}/embed_shaders_script.cmake")
    set(_inputs_quoted "")
    foreach(_s IN LISTS SES_SHADERS)
        get_filename_component(_abs "${_s}" ABSOLUTE)
        list(APPEND _inputs_quoted "\"${_abs}\"")
    endforeach()
    string(REPLACE ";" "\n    " _inputs_block "${_inputs_quoted}")

    file(WRITE "${_script}" "
# Auto-generated by EmbedShaders.cmake. Do not edit.
set(_inputs
    ${_inputs_block}
)
set(_out \"${SES_OUTPUT}\")
file(WRITE \"\${_out}\"
\"/* Auto-generated by EmbedShaders.cmake. Do not edit. */\\n\"
\"#ifndef SPIRITTY_SHADERS_EMBED_H\\n\"
\"#define SPIRITTY_SHADERS_EMBED_H\\n\\n\"
)
foreach(_in IN LISTS _inputs)
    get_filename_component(_base \"\${_in}\" NAME)
    string(REPLACE \".glsl\" \"\" _base \"\${_base}\")
    string(REPLACE \".\" \"_\" _sym \"\${_base}\")
    set(_sym \"sp_shader_\${_sym}\")
    file(READ \"\${_in}\" _src)
    # Escape backslashes, double quotes, then split on newlines so the
    # emitted constant is a series of \"...\\n\" string-literal lines.
    string(REPLACE \"\\\\\" \"\\\\\\\\\" _src \"\${_src}\")
    string(REPLACE \"\\\"\" \"\\\\\\\"\" _src \"\${_src}\")
    string(REPLACE \"\\n\" \"\\\\n\\\"\\n\\\"\" _src \"\${_src}\")
    file(APPEND \"\${_out}\" \"static const char \${_sym}[] =\\n\\\"\${_src}\\\";\\n\\n\")
endforeach()
file(APPEND \"\${_out}\" \"#endif /* SPIRITTY_SHADERS_EMBED_H */\\n\")
")

    add_custom_command(
        OUTPUT  "${SES_OUTPUT}"
        COMMAND "${CMAKE_COMMAND}" -P "${_script}"
        DEPENDS ${SES_SHADERS} "${_script}"
        COMMENT "Embedding GLSL shaders -> ${SES_OUTPUT}"
        VERBATIM
    )
endfunction()
